"""Stage 1: vertical alignment from the vertical mass distribution.

Two claims are load-bearing and both are tested rather than asserted in prose:

1. The vertical mass distribution of a projection is **invariant under rotation about
   the vertical axis**. That is *why* aligning it is a well-posed 1-D registration with
   a unique answer, and why no reconstruction is needed. If it were not invariant the
   whole stage would be measuring the tomographic signal and calling it misalignment.
2. Profile registration versus the centroid, measured rather than assumed. Both
   estimators are fed exactly the same profiles here, so the comparison isolates the
   estimator, and the result is not uniformly in the new method's favour: with the
   sample fully inside the frame the centroid is *exact* and cannot be beaten, and under
   truncation both fail with the correlation failing *worse*. What registration actually
   buys is immunity to localised corruption -- an artifact parked in the vacuum drags a
   centroid by 1.45 px and a correlation peak by nothing. The table in ``vertical.py``'s
   docstring is regenerated by the tests below, and the assertions are written so that
   the docstring cannot drift away from the measurement without a test failing.

numpy + scipy only; no tomopy, no GPU, no beamtime data.
"""

from __future__ import annotations

import numpy as np
import pytest
from scipy.ndimage import fourier_shift, rotate

from tktomo.ptycho_align.core.vertical import (
    TruncationError,
    VerticalConfig,
    align_profiles,
    align_vertical,
    register_profile,
    truncation_flags,
    vertical_profiles,
)


# -- synthetic data ------------------------------------------------------------------


def phantom_stack(size: int = 40, n_slices: int = 32, n_angles: int = 24) -> np.ndarray:
    """Forward-project a numpy-only 3-D phantom by rotate-and-sum.

    Deliberately crude (nearest-to-cubic interpolation, no backend): this test is about
    the invariance of a row-sum, not about projector accuracy, and using a real
    projector would make the test need tomopy.
    """
    from tktomo.io.phantom import generate_volume  # numpy only, no skimage on this path

    volume = generate_volume(size=size, n_slices=n_slices)  # (n_slices, size, size)
    # Pad in-plane so a rotation never clips the object out of the array.
    pad = size // 4
    volume = np.pad(volume, ((0, 0), (pad, pad), (pad, pad)))

    angles_deg = np.linspace(0.0, 180.0, n_angles, endpoint=False)
    stack = np.stack(
        [
            rotate(volume, angle, axes=(1, 2), reshape=False, order=3, mode="constant").sum(axis=1)
            for angle in angles_deg
        ]
    ).astype(np.float32)
    # Vertical vacuum margin, exactly as examples/make_phantom.py pads before shifting:
    # without it the phantom body reaches the first and last detector row, the sample is
    # genuinely truncated, and the truncation detector is right to complain.
    return np.pad(stack, ((0, 0), (12, 12), (0, 0)))


def fourier_shift_rows(stack: np.ndarray, dy: np.ndarray) -> np.ndarray:
    """Exactly translate each projection vertically by ``dy[i]`` rows (positive = down)."""
    out = np.empty_like(stack, dtype=np.float64)
    for i, shift in enumerate(dy):
        out[i] = np.fft.ifftn(fourier_shift(np.fft.fftn(stack[i]), (shift, 0.0))).real
    return out


def gaussian_profile(rows: np.ndarray, centre: float, width: float, height: float = 1.0):
    return height * np.exp(-0.5 * ((rows - centre) / width) ** 2)


# -- the invariance the whole stage rests on -----------------------------------------


def test_vertical_profile_is_invariant_under_rotation_about_the_vertical_axis():
    """Every angle must produce the same ``m(v)``, because rotation preserves the row.

    This is the property that makes vertical alignment decoupled and cheap. It is
    checked here against a genuine 3-D phantom projected over 180 degrees; the residual
    is interpolation error in the test's own rotate-and-sum projector, not physics.
    """
    stack = phantom_stack()
    profiles, offset = vertical_profiles(stack, subtract_baseline=False)

    assert offset == 0
    assert profiles.shape == (stack.shape[0], stack.shape[1])

    reference = profiles.mean(axis=0)
    scatter = np.linalg.norm(profiles - reference, axis=1) / np.linalg.norm(reference)
    assert scatter.max() < 0.02, (
        "the vertical mass distribution changed with angle by "
        f"{scatter.max():.1%}; the decoupling assumption does not hold"
    )

    # The contrast that makes the point: the HORIZONTAL mass distribution is not
    # invariant at all -- that variation is the tomographic signal, which is exactly why
    # the horizontal shift cannot be solved this way.
    horizontal = np.clip(stack, 0.0, None).sum(axis=1)
    reference_u = horizontal.mean(axis=0)
    scatter_u = np.linalg.norm(horizontal - reference_u, axis=1) / np.linalg.norm(reference_u)
    assert scatter_u.max() > 5 * scatter.max()


# -- recovery of known shifts --------------------------------------------------------


@pytest.fixture(scope="module")
def misaligned():
    """A clean stack, a known vertical misalignment, and the corrupted stack."""
    stack = phantom_stack()
    rng = np.random.default_rng(4)
    dy_true = rng.uniform(-3.0, 3.0, stack.shape[0])
    dy_true -= dy_true.mean()  # the constant mode is unobservable; do not ask for it
    return stack, dy_true, fourier_shift_rows(stack, dy_true)


def test_recovers_known_vertical_shifts_well_inside_the_accuracy_target(misaligned):
    """THE GATE for stage 1: recovery error must beat 1/3 of a voxel, by a lot.

    ``sy`` is the *correction*, so a sample displaced downward by ``d`` (positive rows)
    needs ``sy = +d``; recovering ``dy_true`` itself is therefore the right target.
    """
    _stack, dy_true, corrupted = misaligned
    result = align_vertical(corrupted)

    error = float(np.sqrt(np.mean((result.sy - dy_true) ** 2)))
    assert result.converged
    assert error < 0.05, f"vertical recovery error {error:.4f} px (target: < 1/3 px)"
    assert error < 1.0 / 3.0  # the roadmap's accuracy target, stated explicitly


def test_the_unobservable_constant_mode_is_removed(misaligned):
    """A constant ``sy`` translates the whole volume; left alone it random-walks."""
    _stack, _dy_true, corrupted = misaligned
    result = align_vertical(corrupted)
    assert abs(result.sy.mean()) < 1e-9


def test_converges_and_reports_a_history(misaligned):
    _stack, _dy_true, corrupted = misaligned
    result = align_vertical(corrupted, VerticalConfig(max_iterations=10, tolerance=1e-3))

    assert result.converged
    assert 1 < result.n_iterations <= 10
    updates = [step.rms_update for step in result.history]
    assert updates[-1] < updates[0] / 10, f"updates did not decay: {updates}"
    assert result.history[-1].rms_update < 1e-3
    # The residual is the honest "how well do the profiles now agree" number.
    assert result.history[-1].rms_residual < result.history[0].rms_residual
    assert result.reference_profile is not None
    assert result.aligned_profiles.shape == result.profiles.shape


def test_it_does_not_converge_silently(misaligned):
    """One iteration cannot reach a 1e-9 tolerance; the result must say so."""
    _stack, _dy_true, corrupted = misaligned
    result = align_vertical(corrupted, VerticalConfig(max_iterations=1, tolerance=1e-9))
    assert not result.converged
    assert result.n_iterations == 1


@pytest.mark.parametrize("subpixel", ["upsample", "parabolic"])
def test_both_subpixel_refinements_reach_subpixel(misaligned, subpixel):
    _stack, dy_true, corrupted = misaligned
    result = align_vertical(corrupted, VerticalConfig(subpixel=subpixel, tolerance=1e-3))
    error = float(np.sqrt(np.mean((result.sy - dy_true) ** 2)))
    assert error < 0.15, f"{subpixel} refinement gave {error:.4f} px"


# -- the estimator itself ------------------------------------------------------------


def test_register_profile_sign_convention():
    """``register_profile(reference, profile)`` returns ``d`` with ``profile(v) = reference(v - d)``.

    Same convention as skimage's ``phase_cross_correlation(reference, moving)`` and as
    the engine's registration step, so the value can be *added* to the cumulative shift.
    Flipping it turns the loop from converging into diverging.
    """
    rows = np.arange(128.0)
    reference = gaussian_profile(rows, 64.0, 6.0)
    for truth in (3.0, -5.0, 1.25, -0.4):
        moved = gaussian_profile(rows, 64.0 + truth, 6.0)  # moved(v) = reference(v - truth)
        assert register_profile(reference, moved, upsample=200) == pytest.approx(truth, abs=0.02)


def test_register_profile_rejects_length_mismatch():
    with pytest.raises(ValueError, match="lengths differ"):
        register_profile(np.zeros(10), np.zeros(11))


def test_max_shift_confines_the_search():
    rows = np.arange(128.0)
    reference = gaussian_profile(rows, 40.0, 4.0)
    far = gaussian_profile(rows, 90.0, 4.0)
    # The refinement grid spans the integer peak +/- 1 px, so the bound is max_shift + 1.
    assert abs(register_profile(reference, far, max_shift=5.0)) <= 6.0 + 1e-9


# -- stage 1 costs nothing -----------------------------------------------------------


def test_the_loop_runs_on_profiles_alone_so_it_needs_no_projections(misaligned):
    """The cost claim, made checkable.

    ``align_profiles`` takes an ``(n_angles, n_rows)`` array. Nothing in the iteration
    touches the full stack, no reconstruction backend is imported, and the result is the
    same as running the full entry point. That is what "essentially free compared with
    the horizontal step" means concretely: the expensive object is reduced once, and the
    loop then runs on something ``n_cols`` times smaller.
    """
    _stack, dy_true, corrupted = misaligned
    profiles, _offset = vertical_profiles(corrupted)

    from_profiles = align_profiles(profiles)
    from_stack = align_vertical(corrupted)

    np.testing.assert_allclose(from_profiles.sy, from_stack.sy, atol=1e-9)
    assert float(np.sqrt(np.mean((from_profiles.sy - dy_true) ** 2))) < 0.05


def test_a_single_projection_is_a_no_op():
    result = align_profiles(np.ones((1, 32)))
    assert result.converged and result.sy.shape == (1,)


# -- truncation: the one assumption that can fail ------------------------------------


def structured_profiles(n_angles=16, rows=120, seed=2, mode="inside"):
    """1-D profiles with known shifts, in a chosen failure regime.

    Built in 1-D so the regime is isolated: the object is defined on a taller grid and
    then cropped by a *fixed* detector window, so when it is bigger than the window a
    different amount of mass is lost at each angle -- which is exactly what vertical
    truncation is.

    ``mode``: ``"inside"`` (fully within the frame), ``"one-edge"``, ``"both-edges"``,
    or ``"artifact"`` (fully inside, plus a spurious bright feature parked in the
    vacuum of every third projection -- an unremoved hot region, a missed halo).
    """
    rng = np.random.default_rng(seed)
    dy_true = rng.uniform(-4.0, 4.0, n_angles)
    dy_true -= dy_true.mean()

    pad = 40
    tall = np.arange(rows + 2 * pad, dtype=np.float64)
    profiles = np.empty((n_angles, rows))
    for i, shift in enumerate(dy_true):
        if mode == "one-edge":
            full = (
                gaussian_profile(tall, pad + 95.0 + shift, 25.0)
                + 0.6 * gaussian_profile(tall, pad + 50.0 + shift, 4.0)
                + 0.4 * gaussian_profile(tall, pad + 30.0 + shift, 6.0)
            )
        elif mode == "both-edges":
            full = gaussian_profile(
                tall, pad + rows / 2 + shift, 45.0
            ) + 0.4 * gaussian_profile(tall, pad + rows / 2 - 40.0 + shift, 10.0)
        else:
            full = (
                gaussian_profile(tall, pad + 50.0 + shift, 9.0)
                + 0.6 * gaussian_profile(tall, pad + 72.0 + shift, 4.0)
                + 0.3 * gaussian_profile(tall, pad + 32.0 + shift, 3.0)
            )
        profiles[i] = full[pad : pad + rows]
        if mode == "artifact" and i % 3 == 0:
            profiles[i] += gaussian_profile(np.arange(rows, dtype=np.float64), 108.0, 2.0, 0.35)
    return profiles, dy_true


def centroid_shifts(profiles: np.ndarray) -> np.ndarray:
    """What com.py's vertical estimator does, given the same profiles."""
    rows = np.arange(profiles.shape[1], dtype=np.float64)
    mass = np.clip(profiles, 0.0, None)
    centroid = (mass @ rows) / mass.sum(axis=1)
    return centroid - centroid.mean()


def recovery_error(estimate: np.ndarray, truth: np.ndarray) -> float:
    return float(np.sqrt(np.mean((estimate - truth) ** 2)))


def test_truncation_is_detected_and_explained():
    profiles, _dy = structured_profiles(mode="both-edges")
    flags, reason = truncation_flags(profiles)

    assert flags.any()
    assert reason is not None
    assert "not fully inside the field of view" in reason
    assert "row_range" in reason  # the reason must say what to do about it


def test_truncation_can_be_made_fatal():
    profiles, _dy = structured_profiles(mode="both-edges")
    stack = np.repeat(profiles[:, :, None], 4, axis=2) / 4.0

    with pytest.raises(TruncationError, match="not fully inside the field of view"):
        align_vertical(stack, VerticalConfig(on_truncation="raise", subtract_baseline=False))

    # ...and by default it warns and flags rather than refusing, because a little edge
    # contact is common and usually survivable -- but never silently.
    result = align_vertical(stack, VerticalConfig(on_truncation="warn", subtract_baseline=False))
    assert result.truncation_reason is not None
    assert result.truncated.any()

    ignored = align_vertical(stack, VerticalConfig(on_truncation="ignore", subtract_baseline=False))
    assert ignored.truncation_reason is not None  # still reported on the result


def test_a_clean_stack_is_not_flagged(misaligned):
    _stack, _dy, corrupted = misaligned
    result = align_vertical(corrupted)
    assert result.truncation_reason is None
    assert not result.truncated.any()


def test_the_centroid_is_exact_when_the_sample_is_fully_inside_the_frame():
    """The roadmap's claim that CoM is defensible *vertically*, checked.

    Translating a compactly supported mass distribution moves its centroid by exactly
    the translation, so in this regime the centroid is not merely adequate, it is exact,
    and profile registration can only match it. Anyone proposing to replace CoM-vertical
    should know that this is the baseline they are up against.
    """
    profiles, dy_true = structured_profiles(mode="inside")

    centroid = recovery_error(centroid_shifts(profiles), dy_true)
    registered = recovery_error(align_profiles(profiles, VerticalConfig(tolerance=1e-3)).sy, dy_true)

    assert centroid < 0.01, f"the centroid should be exact here, got {centroid:.4f} px"
    assert registered < 0.05, f"registration must match it, got {registered:.4f} px"


@pytest.mark.parametrize("mode", ["one-edge", "both-edges"])
def test_truncation_defeats_both_estimators_which_is_why_it_must_be_flagged(mode):
    """The uncomfortable result, kept in the suite so it is not quietly forgotten.

    Under truncation neither estimator is usable, and cross-correlation is *worse* than
    the centroid, not better: the fixed detector window becomes a strong stationary
    feature that the correlation partly locks onto while the object slides past it. So
    truncation is not a regime this stage survives -- it is one it has to detect, and
    :func:`truncation_flags` firing here is the actual deliverable.
    """
    profiles, dy_true = structured_profiles(mode=mode)

    centroid = recovery_error(centroid_shifts(profiles), dy_true)
    registered = recovery_error(align_profiles(profiles, VerticalConfig(tolerance=1e-3)).sy, dy_true)

    assert centroid > 1.0 / 3.0, f"expected the centroid to break; got {centroid:.3f} px"
    assert registered > 1.0 / 3.0, f"expected registration to break; got {registered:.3f} px"
    assert registered > centroid, (
        "the ranking documented in vertical.py has changed: registration "
        f"{registered:.3f} px vs centroid {centroid:.3f} px -- update the docstring table"
    )
    flags, reason = truncation_flags(profiles)
    assert flags.any() and reason is not None, "the failure was not detected"


def test_an_artifact_in_the_vacuum_drags_the_centroid_but_not_the_correlation():
    """The real practical argument for registering the profile shape.

    A centroid is a global first moment, so a spurious bright feature parked out in the
    vacuum pulls it in proportion to its lever arm even though the sample has not moved.
    A correlation peak is local and does not care, and a median reference across angle
    absorbs the odd bad projection on top of that.
    """
    profiles, dy_true = structured_profiles(mode="artifact")

    centroid = recovery_error(centroid_shifts(profiles), dy_true)
    registered = recovery_error(align_profiles(profiles, VerticalConfig(tolerance=1e-3)).sy, dy_true)

    assert centroid > 1.0, f"the artifact should wreck the centroid; got {centroid:.3f} px"
    assert registered < 0.05, f"registration should ignore it; got {registered:.3f} px"
    assert registered < centroid / 20.0


def test_row_range_is_the_escape_hatch_for_a_truncated_scan(misaligned):
    _stack, dy_true, corrupted = misaligned
    rows = corrupted.shape[1]
    band = (4, rows - 4)  # trims part of the vacuum margin, keeps the whole object

    result = align_vertical(corrupted, VerticalConfig(row_range=band))
    assert result.row_offset == band[0]
    assert result.profiles.shape[1] == band[1] - band[0]
    assert float(np.sqrt(np.mean((result.sy - dy_true) ** 2))) < 0.1


# -- profile construction ------------------------------------------------------------


def test_baseline_subtraction_removes_a_vacuum_pedestal():
    """A residual offset puts a pedestal under every profile, and pedestals dominate
    a cross-correlation. The profile must come back compactly supported."""
    stack = phantom_stack(size=32, n_slices=24, n_angles=6)
    with_offset = stack + 0.05 * np.abs(stack).max()

    raw, _ = vertical_profiles(with_offset, subtract_baseline=False)
    cleaned, _ = vertical_profiles(with_offset, subtract_baseline=True, baseline_rows=4)

    assert raw[:, 0].min() > 0.0  # the pedestal is there
    assert np.allclose(cleaned[:, :2], 0.0, atol=1e-6 * cleaned.max())


def test_clip_negative_makes_the_profile_a_mass_distribution():
    stack = np.zeros((2, 8, 8))
    stack[:, 3, :] = 1.0
    stack[:, 5, :] = -1.0

    clipped, _ = vertical_profiles(stack, clip_negative=True, subtract_baseline=False)
    signed, _ = vertical_profiles(stack, clip_negative=False, subtract_baseline=False)

    assert clipped[0, 5] == 0.0
    assert signed[0, 5] == -8.0


def test_configuration_errors_are_loud():
    stack = np.zeros((2, 8, 8))
    with pytest.raises(ValueError, match="row_range"):
        vertical_profiles(stack, row_range=(4, 2))
    with pytest.raises(ValueError, match="3-D"):
        vertical_profiles(np.zeros((8, 8)))
    with pytest.raises(ValueError, match="2-D"):
        align_profiles(np.zeros((2, 8, 8)))
    with pytest.raises(ValueError, match="reference"):
        align_profiles(np.ones((3, 16)), VerticalConfig(reference="mode"))
    with pytest.raises(ValueError, match="subpixel"):
        register_profile(np.ones(16), np.ones(16), subpixel="cubic")
    with pytest.raises(ValueError, match="on_truncation"):
        align_vertical(np.ones((3, 16, 4)), VerticalConfig(on_truncation="explode"))
