"""Headless core of the reprojection alignment app.

Importable and fully usable without PySide6 -- the whole alignment can be scripted
from a notebook. tomopy/skimage/scipy are imported lazily inside functions, so
``import tktomo.ptycho_align.core`` stays light.
"""

from __future__ import annotations

from tktomo.ptycho_align.core.com import (
    ComResult,
    center_is_plausible,
    com_prealign,
    find_center,
)
from tktomo.ptycho_align.core.dataset import (
    COMPONENTS,
    Crop,
    DatasetProblem,
    Hdf5Entry,
    coerce_load_kwargs,
    inspect_dataset,
    jsonable_load_kwargs,
    list_hdf5_datasets,
    load_dataset,
    load_hdf5,
    suggest_hdf5_paths,
    to_real,
)
from tktomo.ptycho_align.core.engine import (
    DIRECT_ALGORITHMS,
    AlignConfig,
    AlignmentEngine,
    Cancelled,
    algorithm_rejects_negatives,
    apply_shifts,
    row_chunk_size,
    shift_update_is_runaway,
)
from tktomo.ptycho_align.core.state import AlignmentState, IterationResult, VolumePolicy
from tktomo.ptycho_align.core.gradient import (
    DOMAINS,
    RAMP_INVARIANT_DOMAINS,
    GradientConfig,
    RegistrationResult,
    image_gradient,
    prepare_field,
    register_stack,
    register_translation,
    taper_window,
)
from tktomo.ptycho_align.core.odstrcil import (
    AngularCoverage,
    LimitedAngleError,
    OdstrcilConfig,
    OdstrcilEngine,
    SeriesAlignerEntry,
    angular_coverage,
    available_series_aligners,
    check_reconstruction_choice,
    default_odstrcil_config,
    get_series_aligner,
    register_series_aligner,
)
from tktomo.ptycho_align.core.vertical import (
    TruncationError,
    VerticalConfig,
    VerticalIteration,
    VerticalResult,
    align_profiles,
    align_vertical,
    register_profile,
    truncation_flags,
    vertical_profiles,
)

__all__ = [
    "COMPONENTS",
    "DIRECT_ALGORITHMS",
    "AlignConfig",
    "AlignmentEngine",
    "AlignmentState",
    "Cancelled",
    "ComResult",
    "Crop",
    "center_is_plausible",
    "DatasetProblem",
    "Hdf5Entry",
    "IterationResult",
    "VolumePolicy",
    "algorithm_rejects_negatives",
    "apply_shifts",
    "coerce_load_kwargs",
    "com_prealign",
    "find_center",
    "inspect_dataset",
    "jsonable_load_kwargs",
    "list_hdf5_datasets",
    "load_dataset",
    "load_hdf5",
    "row_chunk_size",
    "shift_update_is_runaway",
    "suggest_hdf5_paths",
    "to_real",
    # -- Odstrcil-style decoupled alignment (vertical.py / gradient.py / odstrcil.py) --
    "DOMAINS",
    "RAMP_INVARIANT_DOMAINS",
    "AngularCoverage",
    "GradientConfig",
    "LimitedAngleError",
    "OdstrcilConfig",
    "OdstrcilEngine",
    "RegistrationResult",
    "SeriesAlignerEntry",
    "TruncationError",
    "VerticalConfig",
    "VerticalIteration",
    "VerticalResult",
    "align_profiles",
    "align_vertical",
    "angular_coverage",
    "available_series_aligners",
    "check_reconstruction_choice",
    "default_odstrcil_config",
    "get_series_aligner",
    "image_gradient",
    "prepare_field",
    "register_profile",
    "register_series_aligner",
    "register_stack",
    "register_translation",
    "taper_window",
    "truncation_flags",
    "vertical_profiles",
]
